# Generated by Django 4.2.10 on 2024-03-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='superuser',
            new_name='moderator',
        ),
    ]
