# Generated by Django 4.2.10 on 2024-03-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_superuser_userprofile_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
